name: publish
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
env:
  JULIA_CPU_TARGET: "generic"
jobs:
  build_linux:
    name: Build binaries - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: Patch out GPU support
      shell: bash
      run: git apply no_gpu_patches/no_gpu.patch
    # Get a patched version of JuliaC
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(name="JuliaC", version="0.3.8"); Pkg.Apps.add(name="JuliaC", version="0.3.8")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="libMad-ubuntu-x86_64-${{ github.ref_name }}" && cmake --build . --target install --config Release
    - name: tar output
      run: cd build && tar -czf ../libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz libMad-ubuntu-x86_64-${{ github.ref_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-ubuntu-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"

  build_windows:
    name: Build binaries - windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - name: Windows SSH Key workarounds # A horrible hack, see https://github.com/webfactory/ssh-agent/issues/148#issuecomment-2602109257
      shell: bash
      run: |
        mkdir -p $HOME/.ssh
        cat << EOF > $HOME/.ssh/known_hosts
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
        EOF
    - name: Set julia git
      run: echo "JULIA_PKG_USE_CLI_GIT=true" | Out-File -FilePath $env:GITHUB_ENV -Append
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: Patch out GPU support
      shell: bash
      run: git apply no_gpu_patches/no_gpu.patch
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(name="JuliaC", version="0.3.8"); Pkg.Apps.add(name="JuliaC", version="0.3.8")'
    - name: add JuliaC to path
      run: echo "PATH=$HOME\.julia\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: pwsh
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="libMad-windows-x86_64-${{ github.ref_name }}" && cmake --build . --target INSTALL --config Release
    - name: Add interface lib file for MSVC
      run: |
        cd build/libMad-windows-x86_64-${{ github.ref_name }}
        if (!(Test-Path lib)){
          mkdir lib
        }
        cp bin/libMad.dll.a lib/Mad.lib
    - name: tar output
      run: |
        cd build && tar.exe -czf ..\libMad-windows-x86_64-${{ github.ref_name }}.tar.gz libMad-windows-x86_64-${{ github.ref_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-windows-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"

  build_apple:
    name: Build binaries - macos-latest
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: Patch out GPU support
      shell: bash
      run: git apply no_gpu_patches/no_gpu.patch
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(name="JuliaC", version="0.3.8"); Pkg.Apps.add(name="JuliaC", version="0.3.8")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="libMad-apple-aarch64-${{ github.ref_name }}" && cmake --build . --target install --config Release
    - name: tar output
      run: |
        cd build && tar -czf ../libMad-apple-aarch64-${{ github.ref_name }}.tar.gz libMad-apple-aarch64-${{ github.ref_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-apple-aarch64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"

  build_apple_intel:
    name: Build binaries - macos-26-intel
    runs-on: macos-26-intel
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1']
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: ${{ matrix.julia-version }}
    - name: Patch out GPU support
      shell: bash
      run: git apply no_gpu_patches/no_gpu.patch
    - name: install JuliaC
      run: julia -e 'using Pkg; Pkg.add(name="JuliaC", version="0.3.8"); Pkg.Apps.add(name="JuliaC", version="0.3.8")'
    - name: add JuliaC to path
      run: echo "$HOME/.julia/bin" >> "$GITHUB_PATH"
    - name: build libMad
      run: mkdir build && cd build && mkdir install && cmake .. -DCMAKE_INSTALL_PREFIX="libMad-apple-x86_64-${{ github.ref_name }}" && cmake --build . --target install --config Release
    - name: tar output
      run: |
        cd build && tar -czf ../libMad-apple-x86_64-${{ github.ref_name }}.tar.gz libMad-apple-x86_64-${{ github.ref_name }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libMad-apple-x86_64-${{ github.ref_name }}.tar.gz
        asset_name: libMad-apple-x86_64-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        body: "Release ${{ github.ref_name }}"
